default: &default
  adapter: mysql2
  encoding: utf8
  pool: 2
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: 3306
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] || '' %>

development:
  <<: *default
  database: garage_dev

test:
  <<: *default
  database: garage_test 

production:
  <<: *default
  database: garage